# Generated by Django 5.0.7 on 2024-07-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_occurred', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('current_occupancy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AffectedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_families', models.IntegerField()),
                ('affected_persons', models.IntegerField()),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barangay')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disaster')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province')),
            ],
        ),
        migrations.CreateModel(
            name='DamagedHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partially_damaged', models.IntegerField()),
                ('totally_damaged', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affectedarea')),
            ],
        ),
        migrations.CreateModel(
            name='DisplacedPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cum_families', models.IntegerField()),
                ('now_families', models.IntegerField()),
                ('cum_persons', models.IntegerField()),
                ('now_persons', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affectedarea')),
                ('evacuation_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.evacuationcenter')),
            ],
        ),
        migrations.CreateModel(
            name='EarlyRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_started', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affectedarea')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_of_family', models.CharField(max_length=100)),
                ('number_of_members', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affectedarea')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('relationship_to_head', models.CharField(max_length=50)),
                ('is_displaced', models.BooleanField(default=False)),
                ('is_in_evacuation_center', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family')),
            ],
        ),
        migrations.AddField(
            model_name='barangay',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province'),
        ),
        migrations.CreateModel(
            name='ReliefOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food_items', models.IntegerField()),
                ('non_food_items', models.IntegerField()),
                ('financial_assistance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.affectedarea')),
            ],
        ),
        migrations.CreateModel(
            name='SectoralDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
                ('cum_count', models.IntegerField()),
                ('now_count', models.IntegerField()),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.displacedpopulation')),
            ],
        ),
        migrations.CreateModel(
            name='SexAgeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
                ('age_group', models.CharField(max_length=20)),
                ('cum_count', models.IntegerField()),
                ('now_count', models.IntegerField()),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.displacedpopulation')),
            ],
        ),
        migrations.CreateModel(
            name='DROMICReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_areas', models.ManyToManyField(to='core.affectedarea')),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barangay')),
                ('damaged_houses', models.ManyToManyField(to='core.damagedhouse')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disaster')),
                ('displaced_populations', models.ManyToManyField(to='core.displacedpopulation')),
                ('early_recovery', models.ManyToManyField(to='core.earlyrecovery')),
                ('families', models.ManyToManyField(to='core.family')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province')),
                ('relief_operations', models.ManyToManyField(to='core.reliefoperation')),
                ('sectoral_distributions', models.ManyToManyField(to='core.sectoraldistribution')),
                ('sex_age_distributions', models.ManyToManyField(to='core.sexagedistribution')),
            ],
        ),
    ]
